### ISSUE TITLE
Install instructions warning and poetry shell

### ISSUE THREAD

**Issue by krystynak** [amjadraza/langchain-streamlit-docker-template#1]
Trying to deploy locally.  I tried exactly following the readme and I tried doing it inside a conda venv.  I run into a poetry install warning and a problem with the .venv

john@johns-Air Python % git clone https://github.com/amjadraza/langchain-streamlit-docker-template.git
Cloning into 'langchain-streamlit-docker-template'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 70 (delta 31), reused 60 (delta 21), pack-reused 0
Receiving objects: 100% (70/70), 196.08 KiB | 1.23 MiB/s, done.
Resolving deltas: 100% (31/31), done.
john@johns-Air Python % cd langchain-streamlit-docker-template 
john@johns-Air langchain-streamlit-docker-template % poetry install
Creating virtualenv langchain-streamlit-docker-template in /Users/john/Work/Python/langchain-streamlit-docker-template/.venv
Installing dependencies from lock file

Package operations: 65 installs, 0 updates, 0 removals

  • Installing six (1.16.0)
  • Installing attrs (23.1.0)
  • Installing markupsafe (2.1.2)
  • Installing mdurl (0.1.2)
  • Installing numpy (1.24.3)
  • Installing packaging (23.1)
  • Installing pyrsistent (0.19.3)
  • Installing python-dateutil (2.8.2)
  • Installing pytz (2023.3)
  • Installing smmap (5.0.0)
  • Installing tzdata (2023.3)
  • Installing certifi (2023.5.7)
  • Installing charset-normalizer (3.1.0)
  • Installing decorator (5.1.1)
  • Installing entrypoints (0.4)
  • Installing frozenlist (1.3.3)
  • Installing gitdb (4.0.10)
  • Installing idna (3.4)
  • Installing jinja2 (3.1.2)
  • Installing jsonschema (4.17.3)
  • Installing markdown-it-py (2.2.0)
  • Installing marshmallow (3.19.0)
  • Installing multidict (6.0.4)
  • Installing mypy-extensions (1.0.0)
  • Installing pandas (2.0.2)
  • Installing pygments (2.15.1)
  • Installing toolz (0.12.0)
  • Installing typing-extensions (4.6.2)
  • Installing urllib3 (2.0.2)
  • Installing zipp (3.15.0)
  • Installing aiosignal (1.3.1)
  • Installing altair (4.2.2)
  • Installing async-timeout (4.0.2)
  • Installing blinker (1.6.2)
  • Installing cachetools (5.3.1)
  • Installing click (8.1.3)
  • Installing gitpython (3.1.31)
  • Installing importlib-metadata (6.6.0)
  • Installing marshmallow-enum (1.5.1)
  • Installing pillow (9.5.0)
  • Installing protobuf (3.20.3)
  • Installing pyarrow (12.0.0)
  • Installing pydantic (1.10.8)
  • Installing pydeck (0.8.0)
  • Installing pympler (1.0.1)
  • Installing rich (13.3.5)
  • Installing requests (2.31.0)
  • Installing tenacity (8.2.2)
  • Installing toml (0.10.2)
  • Installing tornado (6.3.2)
  • Installing typing-inspect (0.9.0)
  • Installing tzlocal (5.0.1)
  • Installing validators (0.20.0)
  • Installing yarl (1.9.2)
  • Installing aiohttp (3.8.4)
  • Installing dataclasses-json (0.5.7)
  • Installing numexpr (2.8.4)
  • Installing openapi-schema-pydantic (1.2.4)
  • Installing pyyaml (6.0)
  • Installing sqlalchemy (2.0.15)
  • Installing streamlit (1.22.0)
  • Installing tqdm (4.65.0)
  • Installing langchain (0.0.184)
  • Installing openai (0.27.7)
  • Installing streamlit-chat (0.0.2.2)

/Users/john/Work/Python/langchain-streamlit-docker-template/langchain_streamlit_docker_template does not contain any element
john@johns-Air langchain-streamlit-docker-template % poetry shell
Virtual environment already activated: /Users/john/Work/Python/langchain-streamlit-docker-template/.venv
john@johns-Air langchain-streamlit-docker-template %

**Comment by amjadraza** [comment]
I did not try inside `conda`  environment but it should work. Can try deactivating and activating it again? Poetry Shell some time behaves, I had this issue too. However, I can see your environment is activated

**Comment by krystynak** [comment]
I tried it in no venv, totally fresh and got the same result.  However, I was able to use the Docker build / compose up and get it running on my local machine.
