### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by ourlink** [amjadraza/langchain-streamlit-docker-template#3]
While attempting to create a docker container using the docker-compose.yml file I get the following error 
![docker_error](https://github.com/amjadraza/langchain-streamlit-docker-template/assets/10887137/fd061918-cbb9-44dd-ae39-5e5fcaf59cd0)

**Comment by amjadraza** [comment]
Did you create a Docker Image first?

**Comment by ourlink** [comment]
That's what it was, I built the image and it's now working.
I am using Portainer, so I thought I could just bring your github (https://github.com/amjadraza/langchain-streamlit-docker-template) directly into it. But that did not work for me.
Thanks

**Comment by amjadraza** [comment]
I did not try on Portainer, but it it can detect Dockerfile and it should be able to build an image.  Dont know...

**Comment by ourlink** [comment]
Did not work for me. I cloned the git to the machine and ran docker build. I was then able to use the docker-compose command to get the container built.


-------- Original message --------
From: ma-raza ***@***.***>
Date: 8/3/23 9:08 PM (GMT-06:00)
To: amjadraza/langchain-streamlit-docker-template ***@***.***>
Cc: Doug Flitton ***@***.***>, State change ***@***.***>
Subject: Re: [amjadraza/langchain-streamlit-docker-template] docker-compose error (Issue #3)


I did not try on Portainer, but it it can detect Dockerfile and it should be able to build an image. Dont know...
